# Generated by Django 5.2.7 on 2025-10-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=50)),
                ('std_roll_no', models.IntegerField()),
                ('std_division', models.CharField(max_length=10)),
                ('std_standard', models.CharField(choices=[('A', 'A-Division'), ('B', 'B-Division'), ('C', 'C-Division'), ('E', 'E-Division'), ('F', 'F-Division')], max_length=1)),
                ('std_email', models.EmailField(max_length=254, unique=True)),
                ('std_address', models.CharField(max_length=50)),
            ],
        ),
    ]
